spring:
  data:
    redis:
      password: ${SPRING__DATA__REDIS__PASSWORD:}
  datasource:
    password: ${SPRING__DATASOURCE__PASSWORD:}
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: com.back.global.jpa.config.CustomDevPostgreSQLDialect
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
    show-sql: true
logging:
  level:
    com.back: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.hibernate.orm.jdbc.batch: TRACE
    org.springframework.transaction.interceptor: TRACE
custom:
  jwt:
    secretKey: "${CUSTOM__JWT__SECRET_KEY:dev-only-jwt-secret-key-please-change-1234567890}"
