#!/usr/bin/env bash

# Materialize per-service env files from the host compose env (.env.prod).
# Host .env.prod remains the single source for `docker compose --env-file` interpolation.
# Containers must not mount the full .env.prod (blast-radius / HR-56).

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SOURCE_ENV="${1:-${SCRIPT_DIR}/.env.prod}"
BACK_OUT="${SCRIPT_DIR}/.env.back.prod"
CADDY_OUT="${SCRIPT_DIR}/.env.caddy.prod"

if [[ ! -f "${SOURCE_ENV}" ]]; then
  echo "materialize_service_env: missing source env file=${SOURCE_ENV}" >&2
  exit 1
fi

is_caddy_key() {
  case "$1" in
    API_DOMAIN|MONITOR_DOMAIN|GRAFANA_DOMAIN|PROMETHEUS_DOMAIN|CADDY_EMAIL|\
    PROMETHEUS_BASIC_AUTH_USER|PROMETHEUS_BASIC_AUTH_HASH|\
    ADMIN_API_UPSTREAM|READ_API_UPSTREAM)
      return 0
      ;;
    *)
      return 1
      ;;
  esac
}

is_back_key() {
  local key="$1"
  case "${key}" in
    PROD___POSTGRES__PASSWORD|PROD___POSTGRES_EXPORTER__USERNAME|PROD___POSTGRES_EXPORTER__PASSWORD)
      return 1
      ;;
    PROD___SPRING__*|PROD___CUSTOM__*|CUSTOM__*|CUSTOM_*|SPRING__*|MANAGEMENT_*|BACKEND_PROXY_*)
      return 0
      ;;
    *)
      return 1
      ;;
  esac
}

write_filtered_env() {
  local dest="$1"
  local mode="$2"
  local tmp key
  tmp="$(mktemp "${dest}.XXXXXX")"

  {
    printf '# Generated by materialize_service_env.sh from %s\n' "$(basename "${SOURCE_ENV}")"
    printf '# Do not edit by hand; regenerate before compose up.\n'
    while IFS= read -r line || [[ -n "${line}" ]]; do
      if [[ -z "${line}" || "${line}" =~ ^[[:space:]]*# ]]; then
        continue
      fi
      if [[ "${line}" != *=* ]]; then
        continue
      fi
      key="${line%%=*}"
      if [[ "${mode}" == "caddy" ]]; then
        if is_caddy_key "${key}"; then
          printf '%s\n' "${line}"
        fi
      elif [[ "${mode}" == "back" ]]; then
        if is_back_key "${key}"; then
          printf '%s\n' "${line}"
        fi
      fi
    done < "${SOURCE_ENV}"
  } > "${tmp}"

  install -m 600 "${tmp}" "${dest}"
  rm -f "${tmp}"
}

write_filtered_env "${CADDY_OUT}" "caddy"
write_filtered_env "${BACK_OUT}" "back"

echo "materialize_service_env: wrote $(basename "${CADDY_OUT}") and $(basename "${BACK_OUT}")"
